### ISSUE TITLE
maybe licence issue with docs

### ISSUE THREAD

**Issue by rzr** [AnaviTechnology/anavi-infrared#1]
Maybe you could put references to datasheets or explicitly list their licenses if any

it could be missleading to have them in main project licensed under CC

BTW, some might not be relevant too, ie:
https://github.com/AnaviTech/anavi-infrared/blob/master/docs/25R0623.pdf

**Comment by leon-anavi** [comment]
Hi,

Yes, thank you for pointing out this issue. The docs dir was committed by mistake and it is not relevant for this project. I have removed it.

Best regards,
Leon
